- controllerbi.py
- static/uploadfailpagebi.html
- static/uploadpagebi.html
- static/uploadsuccesspagebi.html
Added Upload Fail Page
Updated controllbi.py to add in redirect to upload fail page when message contains "fail"
> Updated Upload Page & Upload Success Page UI

- server/app/modelbi.py
- static/js/Chartbi.js
- added radio buttons to correlation page
> - added filters to drop down boxes to show only numerical variables

- server/app/__init__.py
- server/app/modelbi.py
- static/js/Chartbi.js
-date selection to appear only when requested
> -added more filtering, currently hardcoded

- server/app/__init__.py
- server/app/modelbi.py
- static/js/TableViewbi.js
-Retrieve combined datasets from init.py
> -Change from dropdownlist to combine data sets radio button format

- server/app/modelbi.py
- static/js/Chartbi.js
- static/js/TableViewbi.js
- added empty select buttons when user select company/depot/geographical location filter
- edited spacing of Chartbi.js
> - reduced redundancies in Chartbi.js

- static/js/Chartbi.js
- static/main.css
- static/tablepagebi.html
- Updated chartbi generate button
> - Imported main.css to chartbi

- static/js/TableViewbi.js
- static/main.css
Added Card and Container to CSS
> Updated TableViewbi.js UI

- static/js/TableViewbi.js
- static/main.css
> Added design for tables in TableViewbi.js

- static/js/TableViewbi.js
- static/main.css
Increased width for save button
> Changed naming for save joined datasets button

- server/app/__init__.py
- server/app/modelbi.py
- static/js/TableViewbi.js
-Add a new method in modelbi.py to retrieve varchar & date
> -Change variablelist to set

- package-lock.json
- server/app/__init__.py
- server/app/modelbi.py
- static/js/Chartbi.js
- static/package-lock.json
Reverts Astarcorp/Beyond-Ideas#38
> Revert "Created flexible join by feature"

- static/js/Chartbi.js
- switched combine datasets with variables on correlation page
> - added form validations to correlation page

- server/app/__init__.py
- server/app/modelbi.py
- static/js/TableViewbi.js
Reverts Astarcorp/Beyond-Ideas#47
> Revert "finalise view datasets"

- static/css/main.css
- static/js/TableViewbi.js
- centralised the tables
- set a max width, if exceed a scrollable horizontal bar will appear
> Updated table display

- static/css/main.css
- static/js/Chartbi.js
- static/js/TableViewbi.js
- To be more consistent with Table View Page (labels, color etc)
> Updated Correlation Page UI

- server/app/__init__.py
- server/app/modelbi.py
- static/js/TableViewbi.js
-move the rest of display table html code from displaytablebi() in modelbi.py to tableviewbi.js
-use react map to display the tables in tableviewbi.js
> move display table html code from modelbi.py to tableviewbi.js

- static/css/main.css
- static/js/Chartbi.js
- Better visual of disabled radio buttons
- Submit button can't select and changed to red color when selected datasets cannot combine
> Updated Correlation Page

- static/js/TableViewbi.js
- Fixed Table widths for all (look nicer)
> Updated Table View Page

- server/app/modelbi.py
- static/js/WebCrawlingbi.js
> -Allowed weather crawling's input parameters for more than 1 year

- static/js/TableViewbi.jsx
> Update tableveiewbi.jsx to use panda conda's code to retrieve the user's table

- static/js/TableViewbi.jsx
-fix bug of dropdown list to disable the first option
-add empty check for map
> Fix bugs of dropdown list

- static/css/main.css
- static/js/Chartbi.jsx
- static/js/TableViewbi.jsx
- static/js/WebCrawlingbi.jsx
- static/layout.html
Standardised font and button color with P.C
> Added spinning loading to webcrawling and table view

- server/app/modelbi.py
- static/js/WebCrawlingbi.jsx
1) Able to either save to csv or database in one single session without the need of refreshing the webpage.
2) Added user id behind the table name.
> Update of integration with frontend for weather web crawling.

- static/js/TableViewbi.jsx
- static/package-lock.json
- static/package.json
1) Add search bar, sort & filter function in view datasets
2) See more button to see more for tableview
> Table view:

- server/app/modelbi.py
> Create two data tables for positive & negative sentiment in sentimentAnalysis() in modelbi.py

- server/app/modelbi.py
- set a threshold for positive (>75%), neutral (50%~75%), & negative (<50%)
- updated model
> - removed @user from tweets processing

- server/app/__init__.py
- static/js/AutoChartbi.jsx
- static/js/Chartbi.jsx
solve the submit button bugs of the same datasource when user enter the filter date range
> update of filter function in smart correlation

- static/js/AutoChartbi.jsx
- static/js/Chartbi.jsx
- static/layout.html
Changed retrieved data to crawl data
> Bold the correlation strengths
